version: '3.8'

volumes:
  postgres-kestra-data:
    driver: local
  postgres-zoomcamp-data:
    driver: local
  kestra-storage:
    driver: local

services:
  postgres-kestra:
    image: postgres:15
    container_name: postgres-kestra
    volumes:
      - postgres-kestra-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: kestra
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: k3str4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kestra -d kestra"]
      interval: 30s
      timeout: 10s
      retries: 10

  postgres-zoomcamp:
    image: postgres:15
    container_name: postgres-zoomcamp
    environment:
      POSTGRES_USER: zoomcamp
      POSTGRES_PASSWORD: zoomcamp
      POSTGRES_DB: zoomcamp
    ports:
      - "5433:5432"
    volumes:
      - postgres-zoomcamp-data:/var/lib/postgresql/data

  kestra:
    image: kestra/kestra:latest
    container_name: kestra
    pull_policy: always
    user: "root"
    command: server standalone
    volumes:
      - kestra-storage:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/kestra-wd:/tmp/kestra-wd
      - ./chap02-workflow-orchestration/kestra/flows:/app/flows
    environment:
      KESTRA_CONFIGURATION: |
        datasources:
          postgres:
            url: jdbc:postgresql://postgres-kestra:5432/kestra
            driverClassName: org.postgresql.Driver
            username: kestra
            password: k3str4
        kestra:
          server:
            basicAuth:
              enabled: false
          repository:
            type: postgres
          flows:
            repository:
              type: file
              file:
                path: /app/flows
                watch: true
          storage:
            type: local
            local:
              basePath: "/app/storage"
          queue:
            type: postgres
          tasks:
            tmpDir:
              path: /tmp/kestra-wd/tmp
          url: http://localhost:8080/
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      postgres-kestra:
        condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8085:80"
    depends_on:
      - postgres-kestra
      - postgres-zoomcamp